### ISSUE TITLE
Update to embedded hal 1.0.0

### ISSUE THREAD

**Issue by TeXitoi** [ryankurte/embedded-hal-compat#33]
embedded hal is out. This crate should support it. The README of embedded-hal point to here.

**Comment by thejpster** [comment]
I tried to use this crate and it's unusable because 1.0-rc.1 conflicts with 1.0. This makes it very difficult to have an application with a mix of 0.2 and 1.0 stuff.

**Comment by MabezDev** [comment]
There is a draft PR here: https://github.com/ryankurte/embedded-hal-compat/pull/32 it's currently blocked on how to handle the `&self` & `&mut self` differences.

**Comment by eldruin** [comment]
This has been done in #34, which has now been published in version 0.13.0.
Thanks everybody!
